<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a6f2dff2-7d95-4d84-9827-052aa0444338</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />

    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoKosova.Business\AutoKosova.Business.csproj" />
    <ProjectReference Include="..\AutoKosova.DataAccess\AutoKosova.DataAccess.csproj" />
    <ProjectReference Include="..\AutoKosova.Entity\AutoKosova.Entity.csproj" />
  </ItemGroup>

</Project>