// <auto-generated />
using System;
using AutoKosova.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoKosova.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522195247_AddStripeRentalPaymentTables")]
    partial class AddStripeRentalPaymentTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoKosova.Entity.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"));

                    b.Property<string>("AccountAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AccountCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AccountDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("AccountDeletedByID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AccountDeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AccountEmailConfirmationPIN")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AccountEmailConfirmationPINExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AccountEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AccountEmailVerifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AccountFailPasswordCount")
                        .HasColumnType("int");

                    b.Property<int?>("AccountForgetPasswordPIN")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AccountForgetPasswordPINExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AccountIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("AccountLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AccountLastFailedLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AccountLastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AccountLastPasswordChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccountLastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AccountLockDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AccountLocked")
                        .HasColumnType("bit");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountPasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("AccountPasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("AccountPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountRoleID")
                        .HasColumnType("int");

                    b.Property<string>("AccountTimeZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("AccountID");

                    b.HasIndex("AccountDeletedByID");

                    b.HasIndex("AccountRoleID");

                    b.HasIndex("TenantID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AutoKosova.Entity.AccountRole", b =>
                {
                    b.Property<int>("AccountRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountRoleID"));

                    b.Property<string>("AccountRoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountRoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountRoleID");

                    b.ToTable("AccountRoles");
                });

            modelBuilder.Entity("AutoKosova.Entity.AccountRolePermission", b =>
                {
                    b.Property<int>("AccountRolePermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountRolePermissionID"));

                    b.Property<int>("AccountRoleID")
                        .HasColumnType("int");

                    b.Property<DateTime>("AccountRolePermissionCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermissionID")
                        .HasColumnType("int");

                    b.HasKey("AccountRolePermissionID");

                    b.HasIndex("AccountRoleID");

                    b.HasIndex("PermissionID");

                    b.ToTable("AccountRolePermissions");
                });

            modelBuilder.Entity("AutoKosova.Entity.CarFavorite", b =>
                {
                    b.Property<int>("CarFavoriteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarFavoriteID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CarFavoriteCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CarFavoriteDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CarFavoriteDeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.HasKey("CarFavoriteID");

                    b.HasIndex("CarID");

                    b.HasIndex("AccountID", "CarID")
                        .IsUnique();

                    b.ToTable("CarFavorites");
                });

            modelBuilder.Entity("AutoKosova.Entity.CarFeature", b =>
                {
                    b.Property<int>("CarFeatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarFeatureID"));

                    b.Property<DateTime>("CarFeatureCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CarFeatureDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CarFeatureDeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CarFeatureDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CarFeatureIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("CarFeatureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarFeatureOrderNumber")
                        .HasColumnType("int");

                    b.HasKey("CarFeatureID");

                    b.ToTable("CarFeatures");
                });

            modelBuilder.Entity("AutoKosova.Entity.CarFeatureMapping", b =>
                {
                    b.Property<int>("CarFeatureMappingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarFeatureMappingID"));

                    b.Property<int>("CarFeatureID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CarFeatureMappingCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CarFeatureMappingDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CarFeatureMappingDeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.HasKey("CarFeatureMappingID");

                    b.HasIndex("CarFeatureID");

                    b.HasIndex("CarID", "CarFeatureID")
                        .IsUnique();

                    b.ToTable("CarFeatureMappings");
                });

            modelBuilder.Entity("AutoKosova.Entity.CarImage", b =>
                {
                    b.Property<int>("CarImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarImageID"));

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<string>("CarImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CarImageCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CarImageDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CarImageDeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CarImageIsMain")
                        .HasColumnType("bit");

                    b.Property<int>("CarImageOrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("CarImageOriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("CarImageSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("CarImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarImageID");

                    b.HasIndex("CarID");

                    b.ToTable("CarImages");
                });

            modelBuilder.Entity("AutoKosova.Entity.Cars", b =>
                {
                    b.Property<int>("CarsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarsID"));

                    b.Property<string>("CarBodyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CarCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CarDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CarDeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CarDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarFuelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarMileage")
                        .HasColumnType("int");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarTransmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CarUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CarYear")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByAccountID")
                        .HasColumnType("int");

                    b.Property<bool>("IsForRent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("bit");

                    b.Property<decimal?>("RentalDailyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("CarsID");

                    b.HasIndex("CreatedByAccountID");

                    b.HasIndex("TenantID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("AutoKosova.Entity.EmailQueue", b =>
                {
                    b.Property<int>("EmailQueueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailQueueID"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("EmailQueueID");

                    b.ToTable("EmailQueues");
                });

            modelBuilder.Entity("AutoKosova.Entity.PaymentEvent", b =>
                {
                    b.Property<int>("PaymentEventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentEventID"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentOrderID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StripeCheckoutSessionID")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StripeEventID")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StripePaymentIntentID")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PaymentEventID");

                    b.HasIndex("PaymentOrderID");

                    b.HasIndex("StripeEventID")
                        .IsUnique();

                    b.ToTable("PaymentEvents");
                });

            modelBuilder.Entity("AutoKosova.Entity.PaymentOrder", b =>
                {
                    b.Property<int>("PaymentOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentOrderID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("FailedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PaymentStatusID")
                        .HasColumnType("int");

                    b.Property<int>("RentalBookingID")
                        .HasColumnType("int");

                    b.Property<string>("StripeCheckoutSessionID")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StripePaymentIntentID")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PaymentOrderID");

                    b.HasIndex("AccountID");

                    b.HasIndex("PaymentStatusID");

                    b.HasIndex("RentalBookingID");

                    b.ToTable("PaymentOrders");
                });

            modelBuilder.Entity("AutoKosova.Entity.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentStatusID"));

                    b.Property<string>("PaymentStatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentStatusID");

                    b.HasIndex("PaymentStatusName")
                        .IsUnique();

                    b.ToTable("PaymentStatuses");

                    b.HasData(
                        new
                        {
                            PaymentStatusID = 1,
                            PaymentStatusDescription = "Payment is waiting to be completed.",
                            PaymentStatusName = "Pending"
                        },
                        new
                        {
                            PaymentStatusID = 2,
                            PaymentStatusDescription = "Payment was completed successfully.",
                            PaymentStatusName = "Paid"
                        },
                        new
                        {
                            PaymentStatusID = 3,
                            PaymentStatusDescription = "Payment failed.",
                            PaymentStatusName = "Failed"
                        },
                        new
                        {
                            PaymentStatusID = 4,
                            PaymentStatusDescription = "Payment was cancelled.",
                            PaymentStatusName = "Cancelled"
                        },
                        new
                        {
                            PaymentStatusID = 5,
                            PaymentStatusDescription = "Payment was refunded.",
                            PaymentStatusName = "Refunded"
                        });
                });

            modelBuilder.Entity("AutoKosova.Entity.Permission", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionID"));

                    b.Property<string>("PermissionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PersmissionIsActive")
                        .HasColumnType("bit");

                    b.HasKey("PermissionID");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("AutoKosova.Entity.RentalBooking", b =>
                {
                    b.Property<int>("RentalBookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalBookingID"));

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerAccountID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentalBookingCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RentalBookingDailyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RentalBookingDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RentalBookingDeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RentalBookingEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RentalBookingStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RentalBookingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("RentalBookingTotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RentalBookingUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("RentalBookingID");

                    b.HasIndex("CarID");

                    b.HasIndex("CustomerAccountID");

                    b.HasIndex("TenantID");

                    b.ToTable("RentalBookings");
                });

            modelBuilder.Entity("AutoKosova.Entity.RentalBookingStatus", b =>
                {
                    b.Property<int>("RentalBookingStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalBookingStatusID"));

                    b.Property<string>("RentalBookingStatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RentalBookingStatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RentalBookingStatusID");

                    b.HasIndex("RentalBookingStatusName")
                        .IsUnique();

                    b.ToTable("RentalBookingStatuses");

                    b.HasData(
                        new
                        {
                            RentalBookingStatusID = 1,
                            RentalBookingStatusDescription = "Booking is waiting for payment.",
                            RentalBookingStatusName = "PendingPayment"
                        },
                        new
                        {
                            RentalBookingStatusID = 2,
                            RentalBookingStatusDescription = "Booking payment is confirmed.",
                            RentalBookingStatusName = "Confirmed"
                        },
                        new
                        {
                            RentalBookingStatusID = 3,
                            RentalBookingStatusDescription = "Booking has been cancelled.",
                            RentalBookingStatusName = "Cancelled"
                        },
                        new
                        {
                            RentalBookingStatusID = 4,
                            RentalBookingStatusDescription = "Booking has been completed.",
                            RentalBookingStatusName = "Completed"
                        });
                });

            modelBuilder.Entity("AutoKosova.Entity.Tenant", b =>
                {
                    b.Property<int>("TenantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantID"));

                    b.Property<int?>("OwnerAccountID")
                        .HasColumnType("int");

                    b.Property<string>("TenantAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantBusinessNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TenantCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TenantIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantID");

                    b.HasIndex("OwnerAccountID");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("AutoKosova.Entity.TenantRequest", b =>
                {
                    b.Property<int>("TenantRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantRequestID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("AdminComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedTenantID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByAccountID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantRequestID");

                    b.HasIndex("AccountID");

                    b.HasIndex("CreatedTenantID");

                    b.HasIndex("ReviewedByAccountID");

                    b.ToTable("TenantRequests");
                });

            modelBuilder.Entity("AutoKosova.Entity.Account", b =>
                {
                    b.HasOne("AutoKosova.Entity.Account", "AccountDeletedBy")
                        .WithMany()
                        .HasForeignKey("AccountDeletedByID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AutoKosova.Entity.AccountRole", "AccountRole")
                        .WithMany()
                        .HasForeignKey("AccountRoleID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AutoKosova.Entity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AccountDeletedBy");

                    b.Navigation("AccountRole");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AutoKosova.Entity.AccountRolePermission", b =>
                {
                    b.HasOne("AutoKosova.Entity.AccountRole", "AccountRole")
                        .WithMany()
                        .HasForeignKey("AccountRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoKosova.Entity.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountRole");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("AutoKosova.Entity.CarFavorite", b =>
                {
                    b.HasOne("AutoKosova.Entity.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AutoKosova.Entity.Cars", "Car")
                        .WithMany()
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("AutoKosova.Entity.CarFeatureMapping", b =>
                {
                    b.HasOne("AutoKosova.Entity.CarFeature", "CarFeature")
                        .WithMany("CarFeatureMappings")
                        .HasForeignKey("CarFeatureID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AutoKosova.Entity.Cars", "Car")
                        .WithMany("CarFeatureMappings")
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("CarFeature");
                });

            modelBuilder.Entity("AutoKosova.Entity.CarImage", b =>
                {
                    b.HasOne("AutoKosova.Entity.Cars", "Car")
                        .WithMany("CarImages")
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("AutoKosova.Entity.Cars", b =>
                {
                    b.HasOne("AutoKosova.Entity.Account", "CreatedByAccount")
                        .WithMany("CreatedCars")
                        .HasForeignKey("CreatedByAccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AutoKosova.Entity.Tenant", "Tenant")
                        .WithMany("Cars")
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAccount");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AutoKosova.Entity.PaymentEvent", b =>
                {
                    b.HasOne("AutoKosova.Entity.PaymentOrder", "PaymentOrder")
                        .WithMany()
                        .HasForeignKey("PaymentOrderID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PaymentOrder");
                });

            modelBuilder.Entity("AutoKosova.Entity.PaymentOrder", b =>
                {
                    b.HasOne("AutoKosova.Entity.Account", "Account")
                        .WithMany("PaymentOrders")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AutoKosova.Entity.PaymentStatus", "PaymentStatus")
                        .WithMany("PaymentOrders")
                        .HasForeignKey("PaymentStatusID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AutoKosova.Entity.RentalBooking", "RentalBooking")
                        .WithMany("PaymentOrders")
                        .HasForeignKey("RentalBookingID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("PaymentStatus");

                    b.Navigation("RentalBooking");
                });

            modelBuilder.Entity("AutoKosova.Entity.RentalBooking", b =>
                {
                    b.HasOne("AutoKosova.Entity.Cars", "Car")
                        .WithMany("RentalBookings")
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AutoKosova.Entity.Account", "CustomerAccount")
                        .WithMany("RentalBookings")
                        .HasForeignKey("CustomerAccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AutoKosova.Entity.Tenant", "Tenant")
                        .WithMany("RentalBookings")
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("CustomerAccount");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AutoKosova.Entity.Tenant", b =>
                {
                    b.HasOne("AutoKosova.Entity.Account", "OwnerAccount")
                        .WithMany()
                        .HasForeignKey("OwnerAccountID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OwnerAccount");
                });

            modelBuilder.Entity("AutoKosova.Entity.TenantRequest", b =>
                {
                    b.HasOne("AutoKosova.Entity.Account", "Account")
                        .WithMany("TenantRequests")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AutoKosova.Entity.Tenant", "CreatedTenant")
                        .WithMany("TenantRequests")
                        .HasForeignKey("CreatedTenantID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AutoKosova.Entity.Account", "ReviewedByAccount")
                        .WithMany("ReviewedTenantRequests")
                        .HasForeignKey("ReviewedByAccountID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Account");

                    b.Navigation("CreatedTenant");

                    b.Navigation("ReviewedByAccount");
                });

            modelBuilder.Entity("AutoKosova.Entity.Account", b =>
                {
                    b.Navigation("CreatedCars");

                    b.Navigation("PaymentOrders");

                    b.Navigation("RentalBookings");

                    b.Navigation("ReviewedTenantRequests");

                    b.Navigation("TenantRequests");
                });

            modelBuilder.Entity("AutoKosova.Entity.CarFeature", b =>
                {
                    b.Navigation("CarFeatureMappings");
                });

            modelBuilder.Entity("AutoKosova.Entity.Cars", b =>
                {
                    b.Navigation("CarFeatureMappings");

                    b.Navigation("CarImages");

                    b.Navigation("RentalBookings");
                });

            modelBuilder.Entity("AutoKosova.Entity.PaymentStatus", b =>
                {
                    b.Navigation("PaymentOrders");
                });

            modelBuilder.Entity("AutoKosova.Entity.RentalBooking", b =>
                {
                    b.Navigation("PaymentOrders");
                });

            modelBuilder.Entity("AutoKosova.Entity.Tenant", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("RentalBookings");

                    b.Navigation("TenantRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
