// <auto-generated />
using System;
using AutoKosova.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoKosova.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426151653_AddingAccountsToDb")]
    partial class AddingAccountsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoKosova.Entity.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"));

                    b.Property<string>("AccountAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AccountBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AccountCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AccountDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("AccountDeletedByAccountID")
                        .HasColumnType("int");

                    b.Property<DateTime>("AccountDeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountEmailConfirmationPIN")
                        .HasColumnType("int");

                    b.Property<DateTime>("AccountEmailConfirmationPINExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AccountEmailVerifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AccountFailPasswordCount")
                        .HasColumnType("int");

                    b.Property<int>("AccountForgetPasswordPIN")
                        .HasColumnType("int");

                    b.Property<DateTime>("AccountForgetPasswordPINExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccountGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AccountIDExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccountIDImageBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountIDImageFront")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountKYCRejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AccountLastFailedLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AccountLastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AccountLastPasswordChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccountLastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AccountLockDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AccountLocked")
                        .HasColumnType("bit");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("AccountPasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("AccountPersonalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountPhoneConfirmationPIN")
                        .HasColumnType("int");

                    b.Property<string>("AccountPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AccountPrivacyPolicyAcceptedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccountPrivateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountRoleID")
                        .HasColumnType("int");

                    b.Property<string>("AccountSelfieImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AccountTermsAcceptedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccountTermsVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountTimeZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AccountTwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("AccountUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AccountVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AccountVerifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountID");

                    b.HasIndex("AccountDeletedByAccountID");

                    b.HasIndex("AccountRoleID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AutoKosova.Entity.AccountRole", b =>
                {
                    b.Property<int>("AccountRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountRoleID"));

                    b.Property<string>("AccountRoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountRoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountRoleID");

                    b.ToTable("AccountsRole");
                });

            modelBuilder.Entity("AutoKosova.Entity.Account", b =>
                {
                    b.HasOne("AutoKosova.Entity.Account", "AccountDeletedBy")
                        .WithMany()
                        .HasForeignKey("AccountDeletedByAccountID");

                    b.HasOne("AutoKosova.Entity.AccountRole", "AccountRole")
                        .WithMany()
                        .HasForeignKey("AccountRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountDeletedBy");

                    b.Navigation("AccountRole");
                });
#pragma warning restore 612, 618
        }
    }
}
