// <auto-generated />
using System;
using AutoKosova.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoKosova.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoKosova.Entity.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"));

                    b.Property<string>("AccountAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AccountCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AccountDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("AccountDeletedByID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AccountDeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AccountEmailConfirmationPIN")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AccountEmailConfirmationPINExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AccountEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AccountEmailVerifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AccountFailPasswordCount")
                        .HasColumnType("int");

                    b.Property<int?>("AccountForgetPasswordPIN")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AccountForgetPasswordPINExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AccountIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("AccountLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AccountLastFailedLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AccountLastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AccountLastPasswordChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccountLastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AccountLockDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AccountLocked")
                        .HasColumnType("bit");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountPasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("AccountPasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("AccountPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountRoleID")
                        .HasColumnType("int");

                    b.Property<string>("AccountTimeZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountID");

                    b.HasIndex("AccountDeletedByID");

                    b.HasIndex("AccountRoleID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AutoKosova.Entity.AccountRole", b =>
                {
                    b.Property<int>("AccountRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountRoleID"));

                    b.Property<string>("AccountRoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountRoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountRoleID");

                    b.ToTable("AccountRoles");
                });

            modelBuilder.Entity("AutoKosova.Entity.CarImage", b =>
                {
                    b.Property<int>("CarImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarImageID"));

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CarImageCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CarImageDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CarImageDeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CarImageIsMain")
                        .HasColumnType("bit");

                    b.Property<int>("CarImageOrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("CarImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarImageID");

                    b.HasIndex("CarID");

                    b.ToTable("CarImages");
                });

            modelBuilder.Entity("AutoKosova.Entity.Cars", b =>
                {
                    b.Property<int>("CarsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarsID"));

                    b.Property<string>("CarBodyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CarCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CarDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CarDeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CarDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarFuelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarMileage")
                        .HasColumnType("int");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarTransmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CarUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CarYear")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByAccountID")
                        .HasColumnType("int");

                    b.Property<bool>("IsForRent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("bit");

                    b.Property<decimal?>("RentalDailyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("CarsID");

                    b.HasIndex("CreatedByAccountID");

                    b.HasIndex("TenantID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("AutoKosova.Entity.RentalBooking", b =>
                {
                    b.Property<int>("RentalBookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalBookingID"));

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerAccountID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentalBookingCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RentalBookingDailyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RentalBookingDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RentalBookingDeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RentalBookingEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RentalBookingStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RentalBookingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RentalBookingTotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RentalBookingUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("RentalBookingID");

                    b.HasIndex("CarID");

                    b.HasIndex("CustomerAccountID");

                    b.HasIndex("TenantID");

                    b.ToTable("RentalBookings");
                });

            modelBuilder.Entity("AutoKosova.Entity.Tenant", b =>
                {
                    b.Property<int>("TenantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantID"));

                    b.Property<string>("TenantAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantBusinessNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TenantCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TenantIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantID");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("AutoKosova.Entity.Account", b =>
                {
                    b.HasOne("AutoKosova.Entity.Account", "AccountDeletedBy")
                        .WithMany()
                        .HasForeignKey("AccountDeletedByID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AutoKosova.Entity.AccountRole", "AccountRole")
                        .WithMany()
                        .HasForeignKey("AccountRoleID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AccountDeletedBy");

                    b.Navigation("AccountRole");
                });

            modelBuilder.Entity("AutoKosova.Entity.CarImage", b =>
                {
                    b.HasOne("AutoKosova.Entity.Cars", "Car")
                        .WithMany("CarImages")
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("AutoKosova.Entity.Cars", b =>
                {
                    b.HasOne("AutoKosova.Entity.Account", "CreatedByAccount")
                        .WithMany("CreatedCars")
                        .HasForeignKey("CreatedByAccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AutoKosova.Entity.Tenant", "Tenant")
                        .WithMany("Cars")
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAccount");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AutoKosova.Entity.RentalBooking", b =>
                {
                    b.HasOne("AutoKosova.Entity.Cars", "Car")
                        .WithMany("RentalBookings")
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AutoKosova.Entity.Account", "CustomerAccount")
                        .WithMany("RentalBookings")
                        .HasForeignKey("CustomerAccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AutoKosova.Entity.Tenant", "Tenant")
                        .WithMany("RentalBookings")
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("CustomerAccount");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AutoKosova.Entity.Account", b =>
                {
                    b.Navigation("CreatedCars");

                    b.Navigation("RentalBookings");
                });

            modelBuilder.Entity("AutoKosova.Entity.Cars", b =>
                {
                    b.Navigation("CarImages");

                    b.Navigation("RentalBookings");
                });

            modelBuilder.Entity("AutoKosova.Entity.Tenant", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("RentalBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
