import type { Car, Booking, User } from '../lib/types';

// Mock Users
export const mockUsers = {
    seller: {
        id: '1',
        email: 'seller@autokosova.com',
        firstName: 'Arben',
        lastName: 'Nortasholli',
        role: 'Seller' as const,
        avatar: undefined,
    } as User,
    user: {
        id: '2',
        email: 'user@autokosova.com',
        firstName: 'John',
        lastName: 'Doe',
        role: 'User' as const,
        avatar: undefined,
    } as User,
    admin: {
        id: '3',
        email: 'admin@autokosova.com',
        firstName: 'Admin',
        lastName: 'User',
        role: 'Admin' as const,
        avatar: undefined,
    } as User,
};

// Mock Cars
export const mockCars: Car[] = [
    {
        id: '1',
        brand: 'BMW',
        model: '320i',
        year: 2022,
        type: 'Sedan',
        price: 45,
        priceType: 'daily',
        mileage: 15000,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        seats: 5,
        description: 'Beautiful BMW 320i in excellent condition. Perfect for business trips or leisure travel.',
        images: [
            'https://images.unsplash.com/photo-1552519507-da3effff991c?w=500&h=400&fit=crop',
            'https://images.unsplash.com/photo-1617469767537-b85ba699c72d?w=500&h=400&fit=crop',
        ],
        isFavorite: false,
        isAvailable: true,
        sellerId: '1',
        sellerName: 'Arben Nortasholli',
        createdAt: '2024-01-15T10:00:00Z',
    },
    {
        id: '2',
        brand: 'Mercedes-Benz',
        model: 'C-Class',
        year: 2023,
        type: 'Sedan',
        price: 65,
        priceType: 'daily',
        mileage: 8000,
        fuelType: 'Diesel',
        transmission: 'Automatic',
        seats: 5,
        description: 'Luxury Mercedes-Benz C-Class with premium features and comfortable interior.',
        images: [
            'https://images.unsplash.com/photo-1618843479302-1586dba20209?w=500&h=400&fit=crop',
            'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=500&h=400&fit=crop',
        ],
        isFavorite: true,
        isAvailable: true,
        sellerId: '1',
        sellerName: 'Arben Nortasholli',
        createdAt: '2024-01-10T10:00:00Z',
    },
    {
        id: '3',
        brand: 'Audi',
        model: 'A4',
        year: 2021,
        type: 'Sedan',
        price: 55,
        priceType: 'daily',
        mileage: 25000,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        seats: 5,
        description: 'Sleek and modern Audi A4 with advanced technology features.',
        images: [
            'https://images.unsplash.com/photo-1606611013016-969c19d4d0d2?w=500&h=400&fit=crop',
        ],
        isFavorite: false,
        isAvailable: true,
        sellerId: '1',
        sellerName: 'Arben Nortasholli',
        createdAt: '2024-01-05T10:00:00Z',
    },
    {
        id: '4',
        brand: 'Toyota',
        model: 'Camry',
        year: 2020,
        type: 'Sedan',
        price: 35,
        priceType: 'daily',
        mileage: 45000,
        fuelType: 'Hybrid',
        transmission: 'Automatic',
        seats: 5,
        description: 'Reliable Toyota Camry hybrid - excellent fuel efficiency and low maintenance.',
        images: [
            'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=500&h=400&fit=crop',
        ],
        isFavorite: false,
        isAvailable: true,
        sellerId: '1',
        sellerName: 'Arben Nortasholli',
        createdAt: '2024-01-01T10:00:00Z',
    },
    {
        id: '5',
        brand: 'Honda',
        model: 'CR-V',
        year: 2022,
        type: 'SUV',
        price: 60,
        priceType: 'daily',
        mileage: 12000,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        seats: 5,
        description: 'Spacious Honda CR-V SUV perfect for families and adventures.',
        images: [
            'https://images.unsplash.com/photo-1605559424843-9e4c3ff86b08?w=500&h=400&fit=crop',
        ],
        isFavorite: false,
        isAvailable: false,
        sellerId: '1',
        sellerName: 'Arben Nortasholli',
        createdAt: '2024-01-20T10:00:00Z',
    },
    {
        id: '6',
        brand: 'Ford',
        model: 'Focus',
        year: 2019,
        type: 'Hatchback',
        price: 30,
        priceType: 'daily',
        mileage: 55000,
        fuelType: 'Petrol',
        transmission: 'Manual',
        seats: 5,
        description: 'Compact and fun Ford Focus - perfect for city driving.',
        images: [
            'https://images.unsplash.com/photo-1607818541957-44c7cb47e4d5?w=500&h=400&fit=crop',
        ],
        isFavorite: false,
        isAvailable: true,
        sellerId: '1',
        sellerName: 'Arben Nortasholli',
        createdAt: '2024-01-18T10:00:00Z',
    },
    {
        id: '7',
        brand: 'Volkswagen',
        model: 'Golf',
        year: 2021,
        type: 'Hatchback',
        price: 40,
        priceType: 'daily',
        mileage: 32000,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        seats: 5,
        description: 'Popular Volkswagen Golf with excellent handling and comfort.',
        images: [
            'https://images.unsplash.com/photo-1611818913633-abb9b6c1c3b9?w=500&h=400&fit=crop',
        ],
        isFavorite: false,
        isAvailable: true,
        sellerId: '1',
        sellerName: 'Arben Nortasholli',
        createdAt: '2024-01-12T10:00:00Z',
    },
    {
        id: '8',
        brand: 'Hyundai',
        model: 'Elantra',
        year: 2022,
        type: 'Sedan',
        price: 32,
        priceType: 'daily',
        mileage: 18000,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        seats: 5,
        description: 'Modern Hyundai Elantra with latest technology and safety features.',
        images: [
            'https://images.unsplash.com/photo-1619405399517-4f03ee6e8bdc?w=500&h=400&fit=crop',
        ],
        isFavorite: false,
        isAvailable: true,
        sellerId: '1',
        sellerName: 'Arben Nortasholli',
        createdAt: '2024-01-08T10:00:00Z',
    },
    {
        id: '9',
        brand: 'Kia',
        model: 'Sportage',
        year: 2023,
        type: 'SUV',
        price: 58,
        priceType: 'daily',
        mileage: 5000,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        seats: 5,
        description: 'Brand new Kia Sportage with stunning design and powerful performance.',
        images: [
            'https://images.unsplash.com/photo-1631495486029-88fb5d05c3f8?w=500&h=400&fit=crop',
        ],
        isFavorite: false,
        isAvailable: true,
        sellerId: '1',
        sellerName: 'Arben Nortasholli',
        createdAt: '2024-01-25T10:00:00Z',
    },
    {
        id: '10',
        brand: 'Nissan',
        model: 'Altima',
        year: 2020,
        type: 'Sedan',
        price: 38,
        priceType: 'daily',
        mileage: 42000,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        seats: 5,
        description: 'Comfortable Nissan Altima with great value for money.',
        images: [
            'https://images.unsplash.com/photo-1614162692108-0a3fcd09cd81?w=500&h=400&fit=crop',
        ],
        isFavorite: false,
        isAvailable: true,
        sellerId: '1',
        sellerName: 'Arben Nortasholli',
        createdAt: '2024-01-03T10:00:00Z',
    },
    {
        id: '11',
        brand: 'Renault',
        model: 'Clio',
        year: 2021,
        type: 'Hatchback',
        price: 28,
        priceType: 'daily',
        mileage: 28000,
        fuelType: 'Petrol',
        transmission: 'Manual',
        seats: 5,
        description: 'Cute and efficient Renault Clio perfect for city adventures.',
        images: [
            'https://images.unsplash.com/photo-1571868212624-540fed02e757?w=500&h=400&fit=crop',
        ],
        isFavorite: false,
        isAvailable: true,
        sellerId: '1',
        sellerName: 'Arben Nortasholli',
        createdAt: '2024-01-07T10:00:00Z',
    },
    {
        id: '12',
        brand: 'Tesla',
        model: 'Model 3',
        year: 2023,
        type: 'Sedan',
        price: 80,
        priceType: 'daily',
        mileage: 2000,
        fuelType: 'Electric',
        transmission: 'Automatic',
        seats: 5,
        description: 'Cutting-edge Tesla Model 3 - fully electric with autopilot features.',
        images: [
            'https://images.unsplash.com/photo-1560958089-b8a63eead8cb?w=500&h=400&fit=crop',
        ],
        isFavorite: false,
        isAvailable: true,
        sellerId: '1',
        sellerName: 'Arben Nortasholli',
        createdAt: '2024-01-22T10:00:00Z',
    },
];

// Mock Bookings
export const mockBookings: Booking[] = [
    {
        id: 'BK001',
        carId: '1',
        car: mockCars[0],
        userId: '2',
        startDate: '2024-02-01',
        endDate: '2024-02-05',
        totalPrice: 180,
        status: 'Confirmed',
        createdAt: '2024-01-28T14:30:00Z',
    },
    {
        id: 'BK002',
        carId: '2',
        car: mockCars[1],
        userId: '2',
        startDate: '2024-02-10',
        endDate: '2024-02-15',
        totalPrice: 325,
        status: 'Pending',
        createdAt: '2024-01-29T10:15:00Z',
    },
    {
        id: 'BK003',
        carId: '3',
        car: mockCars[2],
        userId: '2',
        startDate: '2023-12-20',
        endDate: '2023-12-25',
        totalPrice: 275,
        status: 'Completed',
        createdAt: '2023-12-18T09:00:00Z',
    },
];
